# Introduction to NumPy

**NumPy** (Numerical Python) is the core library for numerical computing in Python. It provides the fast, memory-efficient `ndarray` (n-dimensional array) along with a large collection of mathematical operations that run much faster than equivalent pure-Python code.

This notebook covers the fundamentals:
1. Importing the library
2. Data types: the `ndarray`
3. Creating arrays
4. Indexing and slicing arrays
5. Manipulating and comparing arrays (arithmetic, aggregation, reshaping, transposing, dot product, comparisons)
6. Sorting arrays
7. A practical example: turning an image into an array

## 1. Import the Library

By convention, NumPy is imported with the alias `np`. We can check the installed version with `np.__version__`.

In [ ]:
# Import NumPy using the standard "np" alias
import numpy as np

# Print the installed NumPy version
print(np.__version__)

## 2. Data Types: the `ndarray`

NumPy's main data structure is the **`ndarray`** (n-dimensional array). Every array has useful attributes:

- `.shape` — the size along each dimension
- `.ndim` — the number of dimensions
- `.dtype` — the data type of the elements
- `.size` — the total number of elements

### Arrays of different dimensions

Arrays can have one or more dimensions. Below we create a 1D, 2D, and 3D array and inspect their attributes.

In [ ]:
# 1-dimensional array (a vector)
a1 = np.array([1, 2, 3])

# Inspect: shape, number of dimensions, dtype, size, and Python type
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

In [ ]:
# 2-dimensional array (a matrix). Mixing ints and floats makes the whole array float64.
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

In [ ]:
# 3-dimensional array (think: a stack of 2D matrices)
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

### Anatomy of an array

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimension (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-dimensional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

## 3. Creating Arrays

NumPy provides many convenient functions for building arrays without typing every value by hand:

- `np.array()` — from a Python list
- `np.ones()` / `np.zeros()` — filled with 1s / 0s
- `np.arange()` — evenly spaced values in a range
- `np.random.randint()` / `np.random.random()` — random integers / floats

In [7]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [ ]:
# Check the dtype of the array we just created (integers -> int64)
simple_array.dtype

In [9]:
# Create an array of ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [11]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [12]:
# Create an array of zeros
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [14]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[5, 0, 1],
       [4, 9, 9],
       [7, 8, 7],
       [4, 2, 0],
       [8, 6, 0]], dtype=int32)

In [15]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.99846047, 0.17198717, 0.61282385],
       [0.44071057, 0.33199049, 0.93819072],
       [0.09415061, 0.70136878, 0.99897349],
       [0.13957412, 0.5811253 , 0.44308957],
       [0.55104118, 0.88885451, 0.11844797]])

In [ ]:
# Calling it again gives different numbers (no fixed seed -> new random values each run)
np.random.random((5, 3))

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`]

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

In [ ]:
# Set the random seed so the "random" numbers are reproducible
np.random.seed(0)

# Generate the same random integers every time this cell runs (because of the seed)
np.random.randint(10, size=(5, 3))

With `np.random.seed()` set, every time you run the cell above, the same random numbers will be generated.

What if `np.random.seed()` wasn't set?

Every time you run the cell below, a new set of numbers will appear.

## 4. Indexing and Slicing Arrays

Arrays are indexed like Python lists, but with one index per dimension. We can also use slices (`start:stop`) to pull out sub-arrays.

In [ ]:
# Recall our three arrays from earlier
a1

In [ ]:
a2

In [ ]:
a3

### Indexing single elements and rows

A shape is written as `(row, column, ...)` with optional extra dimensions. Indexing with a single number returns the element (1D) or the first sub-array (2D/3D) at that position.

In [ ]:
# 1D: index 0 returns the first element
a1[0]

In [ ]:
# 2D: index 0 returns the first row
a2[0]

In [ ]:
# 3D: index 0 returns the first 2D matrix
a3[0]

In [ ]:
# Get the 2nd row (index 1) of a2
a2[1]

### Slicing across multiple dimensions

For higher-dimensional arrays we can slice each dimension separately, separated by commas. A colon `:` means "take everything" along that dimension.

In [ ]:
# Create a 4-dimensional array of random integers
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

In [ ]:
# Confirm the shape: 2 x 3 x 4 x 5
a4.shape

In [ ]:
# Keep all of the first 3 dimensions, but only the first 4 numbers of the last dimension
a4[:, :, :, :4]

## 5. Manipulating and Comparing Arrays

This section covers the main ways to transform and combine arrays:

* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Aggregation
    * `np.sum()` - faster than Python's `.sum()` for NumPy arrays
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value
    * These work on all `ndarray`'s
        * `a4.min(axis=0)` -- you can use axis as well
* Reshaping
    * `np.reshape()`
* Transposing
    * `a3.T` 
* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

### Arithmetic

Arithmetic operators work **element-wise** on arrays. When shapes differ, NumPy tries to **broadcast** the smaller array across the larger one — but only if the shapes are compatible (otherwise you get a `ValueError`).

In [ ]:
# Our 1D array
a1

In [ ]:
# A 1D array of ones (same length as a1)
ones = np.ones(3)
ones

In [ ]:
# Add two arrays element-wise
a1 + ones

In [ ]:
# Subtract two arrays element-wise
a1 - ones

In [ ]:
# Multiply two arrays element-wise
a1 * ones

In [ ]:
# Our 2D array
a2

In [ ]:
# Broadcasting: the 1D a1 (shape 3) is applied to each row of the 2D a2 (shape 2x3)
a1 * a2

In [ ]:
# This FAILS on purpose: shapes (2,3) and (2,3,3) can't be broadcast together
a2 * a3

In [ ]:
# Our 3D array (shape 2x3x3)
a3

In [ ]:
# Adding a scalar broadcasts it to every element
a2 + 2

In [ ]:
# Also FAILS on purpose: same incompatible shapes (2,3) and (2,3,3)
a2 + a3

In [ ]:
# Divide two arrays element-wise
a1 / ones

In [ ]:
# Floor division (//) divides and rounds down to the nearest whole number
a2 // a1

In [ ]:
# Raise every element to a power
a2 ** 2

In [ ]:
# np.square() is another way to square every element
np.square(a1)

In [ ]:
# Modulo (%) returns the remainder after division
a1 % 2

In [ ]:
# Natural logarithm of each element
np.log(a1)

In [ ]:
# Exponential (e^x) of each element
np.exp(a1)

### Aggregation

Aggregation reduces an array to a single summary value (sum, mean, etc.). NumPy's own functions (`np.sum`, `np.mean`, ...) are far faster than Python's built-ins on NumPy arrays — the timing demo below shows the difference.

In [ ]:
a1

In [ ]:
# Python's built-in sum()
sum(a1)

In [ ]:
# NumPy's sum() - same result, but optimised for arrays
np.sum(a1)

In [ ]:
# Create a large array to compare performance
massive_array = np.random.random(1000000)
massive_array.size, type(massive_array)

In [ ]:
# Time both: on a NumPy array, np.sum() is dramatically faster than Python's sum()
%timeit sum(massive_array)     # Python sum
%timeit np.sum(massive_array)  # NumPy sum

In [ ]:
# For contrast, build a plain Python list of the same size
import random
massive_list = [random.randint(0, 10) for i in range(1000000)]
len(massive_list), type(massive_list)

In [ ]:
# On a Python list the situation reverses: Python's sum() wins, because np.sum()
# must first convert the list to an array. Use NumPy functions on NumPy arrays.
%timeit sum(massive_list)     # Python sum
%timeit np.sum(massive_list)  # NumPy sum

In [ ]:
# Mean (average) of all elements
np.mean(a1)

In [ ]:
# Standard deviation - how spread out the values are
np.std(a1)

In [ ]:
# Variance - the average squared distance from the mean
np.var(a1)

In [ ]:
# Standard deviation equals the square root of the variance
np.sqrt(np.var(a1))

**What's mean?**

Mean is the same as average. You can find the average of a set of numbers by adding them up and dividing them by how many there are.

**What's standard deviation?**

[Standard deviation](https://www.mathsisfun.com/data/standard-deviation.html) is a measure of how spread out numbers are.

**What's variance?**

The [variance](https://www.mathsisfun.com/data/standard-deviation.html) is the averaged squared differences of the mean.

The standard deviation is the square root of the variance


### Reshaping

`.reshape()` changes an array's shape without changing its data. This is often used to make shapes compatible for broadcasting — for example, reshaping `a2` so it can be combined with `a3`.

In [ ]:
a2

In [ ]:
# a2 is shape (2, 3)
a2.shape

In [ ]:
# FAILS on purpose: (2,3) and (2,3,3) are not broadcast-compatible as-is
a2 + a3

In [ ]:
# Reshape a2 to (2, 3, 1) so it can broadcast against a3 (2, 3, 3), then add
a2.reshape(2, 3, 1) + a3

### Transpose

Transposing flips an array's axes — rows become columns and vice versa. Use `.T` (shorthand) or `.transpose()`. A `(2, 3)` array becomes `(3, 2)`.

In [ ]:
# Original shape (2, 3)
a2.shape

In [ ]:
# Transpose with .T (rows <-> columns)
a2.T

In [ ]:
# .transpose() does the same thing as .T
a2.transpose()

In [ ]:
# The transposed shape is (3, 2)
a2.T.shape

In [ ]:
# A 3D array to show transposing on higher dimensions
matrix = np.random.random(size=(5, 3, 3))
matrix

In [ ]:
# Original shape (5, 3, 3)
matrix.shape

In [ ]:
# Transpose reverses the order of all axes
matrix.T

In [ ]:
# (5, 3, 3) becomes (3, 3, 5) - the axes are reversed
matrix.T.shape

## Dot product


The main two rules for dot product to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
  
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`
 
**Note:** In NumPy, `np.dot()` and `@` can be used to acheive the same result for 1-2 dimension arrays. However, their behaviour begins to differ at arrays with 3+ dimensions.

In [ ]:
# Create two matrices whose inner dimensions match: (3,3) and (3,2)
np.random.seed(0)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

mat1.shape, mat2.shape

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
# Dot product (matrix multiplication): (3,3) @ (3,2) -> (3,2)
np.dot(mat1, mat2)

In [ ]:
# The @ operator is shorthand for np.dot() (same result here)
mat1 @ mat2

In [ ]:
# Two (4,3) matrices - their inner dimensions (3 and 4) do NOT match for a dot product
np.random.seed(0)
mat3 = np.random.randint(10, size=(4, 3))
mat4 = np.random.randint(10, size=(4, 3))
mat3.shape, mat3.shape

In [ ]:
# FAILS on purpose: (4,3) @ (4,3) - inner dimensions 3 and 4 don't align
np.dot(mat3, mat4)

In [ ]:
# Transposing mat3 gives shape (3, 4), which fixes the alignment
mat3.T.shape

In [ ]:
# Now (3,4) @ (4,3) works and produces a (3,3) result
np.dot(mat3.T, mat4)

In [ ]:
# Note: * is element-wise multiplication, NOT the dot product
mat3 * mat4

### Comparison operators 

Finding out if one array is larger, smaller or equal to another.

In [ ]:
a1

In [ ]:
a2

In [ ]:
# Element-wise comparison: returns a boolean array (True/False for each element)
a1 > a2

In [ ]:
# Greater-than-or-equal, element-wise
a1 >= a2

In [ ]:
# Compare every element against a single number (broadcasting)
a1 > 5

In [ ]:
# Equality check, element-wise (an array always equals itself)
a1 == a1

## 6. Sorting Arrays

* [`np.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) - sort values in a specified dimension of an array.
* [`np.argsort()`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) - return the indices to sort the array on a given axis.
* [`np.argmax()`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) - return the index/indicies which gives the highest value(s) along an axis.
* [`np.argmin()`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) - return the index/indices which gives the lowest value(s) along an axis.

In [ ]:
# A random array to sort
random_array

In [ ]:
# Sort the values within each row (ascending)
np.sort(random_array)

In [ ]:
# Return the indices that WOULD sort each row (instead of the sorted values)
np.argsort(random_array)

In [ ]:
a1

In [ ]:
# Index of the largest value in a1
np.argmax(a1)

In [ ]:
a2

In [ ]:
# Without an axis, argmax treats the array as flattened (index 5 = the last element)
np.argmax(a2)

In [ ]:
# axis=1 finds the index of the max within each row
np.argmax(a2, axis=1)

In [ ]:
# Index of the smallest value in a1
np.argmin(a1)

## 7. Practical Example: an Image is Just an Array

Computers store images as numbers, so NumPy can represent any image as an `ndarray`. Reading `horse.png` gives a 3D array of shape `(height, width, channels)`, where each pixel holds its Red, Green, Blue, and Alpha (transparency) values between 0 and 1.

In [ ]:
# Read an image file into a NumPy array
from matplotlib.image import imread

horse = imread('horse.png')
print(type(horse))

In [ ]:
# Shape is (height, width, channels) - here 148 x 178 pixels with 4 channels (RGBA)
horse.shape

In [ ]:
# The raw pixel values - just a big array of numbers between 0 and 1
horse

## Summary

In this notebook we covered the NumPy essentials:

- **The `ndarray`** — n-dimensional arrays and their attributes (`.shape`, `.ndim`, `.dtype`, `.size`).
- **Creating arrays** — `np.array()`, `np.ones()`, `np.zeros()`, `np.arange()`, and random arrays (with `np.random.seed()` for reproducibility).
- **Indexing & slicing** — one index per dimension; `:` to take everything along an axis.
- **Manipulating arrays** — element-wise arithmetic and **broadcasting**, aggregation (`np.sum`, `np.mean`, `np.std`, `np.var`), reshaping, transposing, the **dot product** (`np.dot` / `@`), and comparison operators.
- **Sorting** — `np.sort`, `np.argsort`, `np.argmax`, `np.argmin`.
- **A real example** — an image is simply a NumPy array of pixel values.

Two key takeaways:
1. Operations are **element-wise** by default; shapes must be compatible (or broadcastable).
2. Use **NumPy's own functions on NumPy arrays** — they are far faster than Python's built-ins.